<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PulseDesk.Core\PulseDesk.Core.csproj" />
    <ProjectReference Include="..\PulseDesk.DataAccess\PulseDesk.DataAccess.csproj" />
  </ItemGroup>

</Project>
